### ISSUE TITLE
Add documentation on how to integrate in another project

### ISSUE THREAD

**Issue by kigster** [zhangsu/ccspec#6] opened 2015-11-01 07:08 UTC
Hi!  I am a bit new to C++ development (coming from ruby) and I would like to use this project for my C/C++ libraries I wrote for Arduino.  But it's not obvious to me how to take an existing project and integrate this library into it.  For example, I would not want my ccspecs to be linked to the main binary/executable in the end, but want to be able to run all the tests prior to building that executable. 

Could you add a paragraph or two in the README describing the intended process?

Thanks!

**Comment by kigster** [comment] 2015-11-01 07:08
For reference I am trying to use CLion with Arduino plugin.

**Comment by legacy-code** [comment] 2015-11-24 21:05
I agree.  It's unclear as to how you would actually use this in an existing project.  

I was playing around and couldn't get the examples shown to work either.  I'm just not sure where to put the spec or what the expectations for adding files to ccspec.

Any additional help would be great!

Thanks!

**Comment by zhangsu** [comment] 2015-12-12 21:24
Hey guys, thanks for the feedback. I just updated README with more details. Let me know what doesn't make sense and I will fine-grain it. :)

**Comment by kigster** [comment] 2015-12-13 00:07
This is wonderful, thanks so much!

**Comment by legacy-code** [comment] 2015-12-13 16:31
This is great.  

I haven't had a chance to do much with it yet, but should soon.  What you've added should be enough to get going with this!

Thanks!

**Comment by Drako** [comment] 2016-06-16 08:57
From the comments I'd guess that the issue is resolved, so why isn't it closed yet?

**Comment by zhangsu** [comment] 2016-06-16 23:54
Closing.

**Closed as completed by zhangsu** 2016-06-16 23:54 UTC
